window.speakerNotes = {
  "0": "Bienvenidos a la guía integral de estudio para la certificación GH-500. Esta presentación abarca los seis dominios del examen, cubriendo la prevención, detección y remediación de vulnerabilidades en el ecosistema GitHub.",
  "1": "La agenda cubre los 6 dominios del examen con especial atención en las características, administración y mejores prácticas de seguridad.",
  "2": "Comenzamos con el Dominio 1, que representa el 15-20% del examen. Aquí entenderemos las suites de seguridad, el ciclo de vida seguro y la diferencia vital entre Code Security y Secret Protection.",
  "3": "Este mapa mental muestra la estructura general de GitHub Advanced Security, dividido en sus tres pilares.",
  "4": "El ciclo SSDLC muestra dónde actúa cada característica de GHAS.",
  "5": "Para aprobar el examen, es crucial entender que GHAS ya no es un solo producto, sino un paraguas para Code Security y Secret Protection, sumado a las características de Supply Chain incluidas en todos los planes.",
  "6": "Entender esta matriz es clave. Lo más importante: Dependency graph NO se puede desactivar en repos públicos. Secret scanning y Code scanning son gratis en repos públicos. Security overview y Push protection para repos siempre requieren licencia (excepto public monitoring).",
  "7": "En GHAS operamos con estrategias de seguridad defensiva. Push protection es el mejor ejemplo de prevention-first porque el secreto nunca llega al historial de Git.",
  "8": "Toda alerta tiene un estado (abierto o cerrado) y una razón de resolución.",
  "9": "Validación rápida. Recuerda que la respuesta correcta muestra por qué el Dashboard no es válido para compliance: porque los datos mutan (ej. si borras un repo o cambia un CVE).",
  "10": "Continuamos con Secret Protection. Este es un dominio clave donde se producen la mayoría de los fallos por no entender el flujo de remediación y el Partner Program.",
  "11": "Cuando un desarrollador se salta el Push Protection, la alerta se genera inmediatamente pero su estado de cierre depende del motivo seleccionado.",
  "12": "Nunca elijas 'reescribir el historial' como la primera opción en el examen. Un secreto ya pudo haber sido clonado. La primera acción siempre es rotar/revocar.",
  "13": "Diagrama del flujo completo de respuesta a credenciales comprometidas.",
  "14": "Los validity checks cambian por completo la prioridad de un triage. Si la credencial dice que sigue activa, el riesgo es extremo. El partner program funciona solo en repos públicos. Secret scanning busca en issues (abiertos y cerrados), PRs y wikis, no solo en el historial del código.",
  "15": "Delegated bypass previene que los desarrolladores usen 'I'll fix it later' sin aprobación. Las solicitudes expiran a los 7 días.",
  "16": "Para evitar los dismissals directos usamos Delegated alert dismissal.",
  "17": "Pasamos a Supply Chain Security. Hay que tener muy clara la diferencia entre Version Updates (que requiere YAML y usa SemVer) y Security Updates (que usa el Grafo de Dependencias).",
  "18": "Las actualizaciones de versión necesitan el dependabot.yml. Las actualizaciones de seguridad no. El dependency graph alimenta todo excepto las Version Updates.",
  "19": "Dependency review action te permite bloquear Pull Requests basándose en licencias prohibidas o severidad de vulnerabilidades.",
  "20": "El SBOM que exporta GHAS siempre es SPDX. Las Artifact Attestations son muy importantes en GHEC para asegurar la procedencia y combatir ataques de inyección de código.",
  "21": "Los updates de version y los de security tienen reglas distintas. Las security updates no se limitan por open-pull-requests-limit.",
  "22": "CVSS mide el daño técnico. EPSS mide la probabilidad. Combinar ambos permite priorizar correctamente.",
  "23": "Las actualizaciones de seguridad siempre van a la versión mínima que soluciona el problema, para evitar romper cambios (breaking changes).",
  "24": "Code Security, especialmente CodeQL. Dominio altamente técnico. Importante diferenciar Default Setup de Advanced Setup.",
  "25": "La query suite 'security-and-quality' no existe en Default Setup, requiere obligatoriamente Advanced Setup.",
  "26": "El permiso security-events: write es OBLIGATORIO para subir los resultados.",
  "27": "GitHub etiqueta las alertas fuera de código de aplicación (Generated, Test, Library, Documentation).",
  "28": "Recuerda que security-and-quality REQUIERE advanced setup. Default setup solo da hasta security-extended.",
  "29": "Para los problemas de 'No source code', la solución suele ser cambiar el build-mode a manual o none.",
  "30": "Una pregunta muy común del examen.",
  "31": "Operaciones de seguridad: cómo lidiar con 5,000 alertas. Hablamos de campañas, CVSS vs EPSS y Security Manager.",
  "32": "EPSS indica probabilidad de explotación en 30 días, mientras CVSS es el impacto si es explotada. Juntas priorizan el riesgo.",
  "33": "Las campañas centralizan los esfuerzos. En código, Autofix genera las correcciones; en secretos, no hay autofix, hay que rotar.",
  "34": "PVR permite un flujo seguro y sin ruido público cuando alguien encuentra una vulnerabilidad en tu código. Y rulesets pueden forzar compliance.",
  "35": "Es vital saber que Security Manager es un rol a nivel de EQUIPO.",
  "36": "Dominio 6: Administración, Security Configurations y Enforcement. Es crucial entender cómo se heredan las políticas.",
  "37": "Todo lo que la empresa o la organización marca como ENFORCE, el repositorio no lo puede cambiar. Si NO tiene enforce, el repositorio lo puede sobreescribir.",
  "38": "Facturación por comitter activo es una métrica clave del examen.",
  "39": "GHES carece de las features 100% cloud como Public Monitoring, y requiere GitHub Connect para descargar advisories.",
  "40": "La API REST es fundamental para aplicar security configurations a miles de repos en masa.",
  "41": "Habilitación masiva y segura.",
  "42": "Lecturas recomendadas para el examen y link al simulador.",
  "43": "Revisión de términos clave del glosario maestro, parte 1 de 5.",
  "44": "Revisión de términos clave del glosario maestro, parte 2 de 5.",
  "45": "Revisión de términos clave del glosario maestro, parte 3 de 5.",
  "46": "Revisión de términos clave del glosario maestro, parte 4 de 5.",
  "47": "Revisión de términos clave del glosario maestro, parte 5 de 5.",
  "48": "Muchas gracias y éxito en el examen GH-500."
};