window.speakerNotes = {
  "0": "Bienvenidos a la Unidad 2. Hoy no solo aprenderemos la teoría, sino que la aplicaremos directamente a su próximo proyecto evaluado: el rediseño del sitio web de la Municipalidad de Cholchol.",
  "1": "Esta es la ruta crítica para aprobar su evaluación sumativa con máxima nota.",
  "2": "Comenzaremos con la teoría detrás de una interfaz verdaderamente útil.",
  "3": "Nuestro marco pedagógico se basa en ensuciarnos las manos rápido.",
  "4": "Peter Morville establece siete facetas para que una interfaz, como la de la municipalidad, sea excelente.",
  "5": "Recuerden: Diseñar no es un proceso de una sola pasada. Para el municipio de Cholchol, investiguen a los vecinos primero.",
  "6": "Accesibilidad no es opcional. CE4 lo exige: etiquetas semánticas, navegación por teclado y contraste de colores.",
  "7": "Como UX Researcher, he visto fracasar productos porque se basaron en suposiciones. Investigar metodológicamente es la única forma de validar decisiones de diseño.",
  "8": "Este es el flujo de trabajo de una agencia experta: de la pregunta de investigación a la recomendación implementable.",
  "9": "Estos son los entregables que un UX Researcher proporciona al equipo de desarrollo para asegurar un producto exitoso.",
  "10": "Haremos un repaso rápido de los fundamentos indispensables que sostienen la web.",
  "11": "Nunca confundan sus roles: HTML para significado, CSS para presentación, y JS para acción.",
  "12": "Una sopa de divs funciona visualmente, pero rompe las reglas de accesibilidad que exige el Criterio 4 de su rúbrica.",
  "13": "Flexbox es su mejor amigo para maquetar barras de navegación y grillas simples.",
  "14": "Si necesitan velocidad, Bootstrap es ideal. Por eso se permite usarlo en su evaluación.",
  "15": "Analicemos el caso evaluado: La municipalidad de Cholchol.",
  "16": "Si van a la web actual, notarán lo anticuada que está. Su labor es traerla a la era moderna.",
  "17": "Esta tabla es su lista de chequeo de la evaluación.",
  "18": "Una aplicación bien estructurada te regala puntaje en CE7 y CE8.",
  "19": "Usaremos VS Code, Prettier y ES7+ React Snippets.",
  "20": "El nombre del archivo que suban DEBE ser en snake_case como indica la rúbrica. Los componentes en PascalCase.",
  "21": "Si entregan todo el código aglomerado en App.jsx, pierden el puntaje del CE7. Dividan sus archivos.",
  "22": "Separar la lógica visual de la lógica de negocio es una práctica top-tier en React.",
  "23": "Aquí entramos en materia densa: el DOM Virtual, inmutabilidad y renderizado condicional.",
  "24": "Modificar el DOM real es lento. React usa un clon en memoria para hacer los cálculos súper rápidos.",
  "25": "Un componente es solo una función JS que retorna HTML (JSX).",
  "26": "Si necesitan que un valor visual cambie en tiempo real, NECESITAN usar `useState`.",
  "27": "Siempre manejen estados vacíos. React adora los `.map()` para construir listas visuales.",
  "28": "Esto resuelve de manera perfecta la exigencia CE3 de agregar/eliminar contenido dinámico.",
  "29": "La interactividad y las validaciones de contacto representan la parte más jugosa de su nota.",
  "30": "Implementando este componente ya tienen sus 3 eventos necesarios para cumplir el CE1.",
  "31": "Este es el esqueleto de un formulario dinámico.",
  "32": "Aquí está la lógica robusta de validación que exige el evaluador.",
  "33": "Con estos 3 fragmentos de código, tienen asegurado el 100% en el CE2 de formularios.",
  "34": "Último bloque: Datos al vuelo y un envoltorio estético profesional.",
  "35": "El evaluador buscará que entiendan cómo cargar datos AL INICIAR el componente.",
  "36": "Esto demuestra manejo del ciclo de vida asíncrono.",
  "37": "Cualquiera que elijan está bien, siempre que la utilicen coherentemente.",
  "38": "Esta es la clave para que la página no se vea aplastada en un celular.",
  "39": "Si estructuran su proyecto de esta forma, tienen la máxima calificación garantizada.",
  "40": "¡Excelente trabajo! Manos a la obra, el municipio los necesita."
};