window.speakerNotes = {
  "0": "Bienvenidos a la Unidad 1 del curso de Desarrollo Frontend. En esta unidad veremos metodologías sólidas de investigación de UX, el diseño centrado en el usuario, las estructuras de páginas web, y los lenguajes básicos HTML, CSS y JS.",
  "1": "El mapa de ruta para esta unidad. Pasaremos por diseño UX/UI, investigación, maquetación y lenguajes web.",
  "2": "Comenzamos con el primer bloque, centrado en cómo construir una experiencia memorable basada en investigación sólida.",
  "3": "El Diseño Centrado en el Usuario es una filosofía de diseño que pone al usuario final en el centro del proceso. Fue popularizado por expertos como Donald Norman. Se basa en comprender necesidades, iterar, colaborar y tener un enfoque holístico.",
  "4": "El trabajo del UX Researcher sigue etapas metódicas: Planificación, Recolección de datos, Análisis y Recomendaciones.",
  "5": "Una herramienta clave de UX Research es el User Persona. No es un invento, se basa en datos reales de la recolección.",
  "6": "Las pruebas de usabilidad son clave. Debemos evitar el sesgo y hacer preguntas neutrales.",
  "7": "Implementar Diseño Centrado en el Usuario aporta beneficios medibles: mejora la experiencia, reduce los costos de corrección y aumenta la fidelidad del cliente.",
  "8": "Pregunta rápida para asegurar la comprensión de la investigación UX.",
  "9": "Ahora que entendemos la usabilidad, veamos cómo se estructuran físicamente las páginas web dependiendo de su objetivo comercial.",
  "10": "Existen múltiples tipos de páginas según su objetivo: la página de Inicio, la de servicios para detallar oferta, la squeeze page para captar leads y la de producto para e-commerce.",
  "11": "La página de producto en un E-commerce tiene elementos muy específicos para generar confianza y conversión, como reseñas, galería, CTA y copys.",
  "12": "Comparativa de usabilidad técnica. Un sitio rápido y accesible es fundamental.",
  "13": "Pregunta de validación sobre diseño responsivo y optimización.",
  "14": "Entramos a la parte técnica: las tecnologías que dan vida al Front-End. HTML, CSS y JS.",
  "15": "HTML define la estructura, CSS la presentación, y JS la interactividad. Juntos construyen la experiencia frontend.",
  "16": "Explicación básica de cómo estructurar un documento HTML.",
  "17": "La organización del código HTML afecta el SEO y la mantenibilidad. Debemos indentar bien y usar semántica.",
  "18": "Explicación de selectores y reglas de CSS.",
  "19": "Interactividad básica con DOM y eventos.",
  "20": "Frameworks como Bootstrap, comparativas y cierre práctico.",
  "21": "Introducción al framework más utilizado para maquetar rápido.",
  "22": "Comparativa corregida con etiquetas HTML en las celdas.",
  "23": "Respiro para recordar que la estética no es nada sin funcionalidad.",
  "24": "Ejercicio práctico para los estudiantes, según los requerimientos de su evaluación.",
  "25": "Enlaces a recursos útiles mencionados en el material.",
  "26": "Fin de la presentación."
};