window.speakerNotes = {
  "0": "En esta unidad comprenderemos por qué dividimos el código en tres capas fundamentales y cómo Spring facilita la manipulación de formularios web y bases de datos.",
  "1": "",
  "2": "",
  "3": "",
  "4": "",
  "5": "",
  "6": "",
  "7": "",
  "8": "",
  "9": "",
  "10": "",
  "11": "",
  "12": "",
  "13": "",
  "14": "",
  "15": "",
  "16": "",
  "17": "",
  "18": "",
  "19": "",
  "20": "",
  "21": "",
  "22": "",
  "23": "",
  "24": "",
  "25": "",
  "26": "",
  "27": "",
  "28": "",
  "29": "",
  "30": "Abrir sesión de Preguntas y Respuestas sobre las responsabilidades del Modelo, Vista y Controlador."
};