window.speakerNotes = {
  "0": "Bienvenidos a la última sesión del curso. Hoy pasaremos de saber programar a dominar la ciencia de datos en Python a un nivel profesional.",
  "1": "Repasaremos todo el camino recorrido e introduciremos técnicas que distinguen a un Junior de un Semi-Senior.",
  "2": "Dejamos claro el peso e importancia de esta etapa.",
  "3": "El 40% de la nota exige dominar todos los conceptos previos.",
  "4": "La meta suprema.",
  "5": "Mirar hacia atrás para ver cuánto hemos crecido.",
  "6": "Cómo subimos la escalera de complejidad técnica.",
  "7": "Las herramientas que el estudiante ya debe dominar a la perfección.",
  "8": "Aquí introducimos conceptos 'intermediarios' que separan al amateur del profesional.",
  "9": "Herramientas que aceleran la escritura y el procesamiento.",
  "10": "El patrón más pitónico.",
  "11": "El combo perfecto para transformaciones al vuelo.",
  "12": "Matplotlib puede hacer mucho más que un simple gráfico de barras.",
  "13": "Una vista de comando (dashboard).",
  "14": "A veces necesitas el número exacto y la forma visual al mismo tiempo.",
  "15": "De cara al examen, cómo abordar un proyecto gigantesco.",
  "16": "Un escenario hipotético de examen.",
  "17": "Cómo administrar el tiempo en un examen de 6 horas.",
  "18": "Consejos dorados antes de la prueba.",
  "19": "Errores comunes que hacen perder puntos tontos.",
  "20": "El mensaje final para los alumnos.",
  "21": "Dónde seguir aprendiendo.",
  "22": "Fin del curso."
};