window.speakerNotes = {
  "0": "Bienvenidos a la asignatura Programación para la Ciencia de Datos. Esta es la unidad cero, donde presentaremos el curso, la metodología y las bases fundamentales.",
  "1": "Hoy revisaremos 5 puntos principales: la presentación del curso, el programa de la asignatura, la metodología, las bases de programación y un caso práctico inicial.",
  "2": "Comenzamos con la introducción general y la presentación del docente.",
  "3": "La programación es la herramienta esencial que nos permite transformar datos brutos en conocimiento accionable.",
  "4": "Me presento brevemente. Soy especialista en ciencias de la computación con años de experiencia aplicada.",
  "5": "Revisemos ahora la estructura del programa de asignatura, las horas y la competencia principal que desarrollaremos.",
  "6": "La asignatura cuenta con 72 horas en total, fuertemente enfocadas en la teoría aplicada y el taller.",
  "7": "El nivel de dominio esperado es 5. Deberán codificar algoritmos completos, desde la entrada hasta la salida.",
  "8": "El curso se divide en 3 unidades principales, culminando con la evaluación final integradora.",
  "9": "Veamos qué contiene exactamente cada una de las 3 unidades de competencia.",
  "10": "En la unidad 1, aprenderemos la base del lenguaje Python y cómo manipular estructuras fundamentales.",
  "11": "La unidad 2 nos llevará a diseñar e implementar algoritmos para limpiar, transformar y validar conjuntos de datos.",
  "12": "Finalmente, en la unidad 3, nos enfocaremos en hacer que nuestro código sea robusto, libre de errores y rápido.",
  "13": "Veamos si recordamos las horas y ponderaciones.",
  "14": "Ahora pasaremos a entender cómo vamos a aprender y cómo seremos evaluados.",
  "15": "El Aprendizaje Basado en Problemas es el corazón de nuestra metodología. No solo escucharemos teoría, sino que la aplicaremos en escenarios reales.",
  "16": "Aquí está el desglose de nuestras 4 notas importantes. Las unidades progresan de 10% a 30%, terminando con el 40% final.",
  "17": "Algunos recordatorios para el desarrollo fluido de las clases prácticas.",
  "18": "Entramos de lleno a repasar los conceptos fundamentales de Python que usaremos.",
  "19": "Python no trabaja solo. Para la ciencia de datos, nos apoyamos en librerías altamente optimizadas.",
  "20": "La indentación es clave en Python. Observemos un ejemplo simple de if/else.",
  "21": "Listas, tuplas y diccionarios sirven para distintos propósitos en la agrupación de información.",
  "22": "Usaremos for la gran mayoría de las veces para recorrer datasets.",
  "23": "Pandas es el estándar para el análisis tabular en Python.",
  "24": "Matplotlib nos permite ver rápidamente disparidades, como la población concentrada en la capital.",
  "25": "Para cerrar la sesión, veamos un caso práctico real que ilustra el flujo de trabajo.",
  "26": "Debemos entregar un informe ejecutivo basado en el cruce de datos demográficos y sanitarios.",
  "27": "Entender los datos es el primer paso antes de programar cualquier algoritmo.",
  "28": "El caso se resuelve en 4 pasos progresivos, desde la carga hasta el reporte.",
  "29": "Una pregunta rápida de reflexión.",
  "30": "Toda esta documentación complementará el aprendizaje.",
  "31": "Muchas gracias por su atención. Estamos listos para arrancar."
};