window.speakerNotes = {
  "0": "Bienvenida a la Unidad 3. Explicaremos los fundamentos de la automatización y el ciclo de vida de los defectos.",
  "1": "Visión general de los 4 capítulos que componen esta unidad.",
  "2": "Iniciamos con el primer tema clave: La Automatización.",
  "3": "Definición de automatización. El uso de software para controlar la ejecución de pruebas.",
  "4": "Comparación directa. Lo manual es susceptible a error y tedioso, lo automatizado es rápido y repetible.",
  "5": "Eficiencia, reducción de costos, mejor cobertura e integración continua.",
  "6": "No todo se automatiza. Pruebas de regresión sí, pruebas exploratorias no.",
  "7": "Pasamos a cómo se gestionan los bugs una vez encontrados.",
  "8": "Un defecto o bug es cualquier desviación del comportamiento esperado.",
  "9": "Desde el reporte hasta el cierre.",
  "10": "La importancia de documentar bien: pasos, entorno, severidad.",
  "11": "Severidad (impacto técnico) vs Prioridad (impacto de negocio).",
  "12": "El desarrollador analiza, codifica la solución y aplica pruebas unitarias.",
  "13": "Asegurar que el parche no rompió nada más.",
  "14": "El ecosistema actual y hacia dónde va el testing.",
  "15": "Selenium, Appium, Cucumber, Robot Framework.",
  "16": "El testing dentro del pipeline DevOps.",
  "17": "Behavior Driven Development (Gherkin) vs Test Driven Development.",
  "18": "Herramientas que graban acciones o usan drag-and-drop.",
  "19": "Self-healing tests y generación de casos con IA.",
  "20": "Estrategias para no fracasar automatizando.",
  "21": "Muchas pruebas unitarias, algunas de integración, pocas de UI.",
  "22": "Automatizar todo, no mantener scripts, ignorar falsos positivos.",
  "23": "Pregunta: ¿Qué tipo de pruebas es mejor dejar manuales?",
  "24": "Resumen final y cierre de la clase."
};