window.speakerNotes = {
  "0": "Bienvenidos a este recorrido profundo. Asumiremos que no sabes nada de Java en la web y terminaremos entendiendo por qué Spring gobierna el mercado mundial.",
  "1": "",
  "2": "",
  "3": "",
  "4": "",
  "5": "",
  "6": "",
  "7": "",
  "8": "",
  "9": "",
  "10": "",
  "11": "",
  "12": "",
  "13": "",
  "14": "",
  "15": "",
  "16": "",
  "17": "",
  "18": "",
  "19": "",
  "20": "",
  "21": "",
  "22": "",
  "23": "",
  "24": "",
  "25": "",
  "26": "",
  "27": "",
  "28": "",
  "29": "Agradecer a los estudiantes y abrir espacio para dudas y consultas."
};