window.speakerNotes = {
  "0": "Bienvenidos a la Unidad 2. Pasaremos de los fundamentos básicos a la construcción de pipelines reales de limpieza y transformación.",
  "1": "Nuestra hoja de ruta incluye desde el diseño algorítmico hasta el cruce de bases de datos heterogéneas.",
  "2": "En la U1 vimos las piezas del lego. Ahora construiremos la nave espacial completa.",
  "3": "El objetivo es claro: crear pipelines automatizados.",
  "4": "Diferencia entre un script de U1 y un pipeline de U2.",
  "5": "Antes de picar código, hay que pensar.",
  "6": "El ciclo típico de un proceso ETL básico.",
  "7": "Entrando a la limpieza profunda.",
  "8": "Los tres jinetes de los datos sucios.",
  "9": "No siempre es buena idea borrar todo.",
  "10": "Cómo encontrar valores atípicos de forma programática.",
  "11": "Cambiando la forma y el significado de los datos.",
  "12": "Un resumen de por qué transformamos la data.",
  "13": "Las fechas como texto son inútiles.",
  "14": "¿Por qué es importante escalar?",
  "15": "Uniendo las piezas dispersas.",
  "16": "La filosofía detrás de groupby.",
  "17": "Cómo actúan los joins.",
  "18": "El caso central: Mineduc e INE.",
  "19": "Contexto de la evaluación de U2.",
  "20": "Qué incluye cada archivo fuente.",
  "21": "Pasos recomendados para la evaluación.",
  "22": "Cómo asegurar que el pipeline funcionó.",
  "23": "La importancia del dataset consolidado.",
  "24": "Cierre con lecturas y material anexo de la plataforma.",
  "25": "Despedida."
};