window.speakerNotes = {
  "0": "Bienvenidos a la Unidad 3. Aprenderemos a hacer que nuestros pipelines no solo funcionen, sino que sean rápidos, seguros y mantenibles.",
  "1": "Nuestra hoja de ruta para dominar el rendimiento en Python.",
  "2": "No podemos optimizar lo que no medimos.",
  "3": "Una regla fundamental de la ingeniería de software.",
  "4": "Cómo auditar la velocidad de nuestro script.",
  "5": "Un pipeline no debe colapsar abruptamente por un dato faltante.",
  "6": "Lo que puede salir mal, saldrá mal.",
  "7": "Cómo atajar errores sin matar el proceso.",
  "8": "El núcleo de la aceleración matemática en Python.",
  "9": "La diferencia entre minutos y milisegundos.",
  "10": "Resumen de técnicas para acelerar.",
  "11": "Asegurando que la optimización no rompió las matemáticas.",
  "12": "El concepto de regresión en pruebas.",
  "13": "Pasar de un notebook sucio a código profesional.",
  "14": "Entrando al eCommerce Mercado Austral.",
  "15": "De qué trata la evaluación final.",
  "16": "Muestra de los CSVs entregados.",
  "17": "Análisis de las fallas requeridas por la pauta.",
  "18": "Cómo estructurar el repositorio.",
  "19": "Cierre inspiracional sobre ingeniería de datos.",
  "20": "Cierre con QR",
  "21": "Fin de Unidad."
};