window.speakerNotes = {
  "0": "Bienvenidos a la Unidad 1. Aquí comenzaremos a construir las bases prácticas de programación orientadas a la manipulación de datos en Python.",
  "1": "Nuestra ruta para hoy cubre desde un repaso de nuestros objetivos hasta el desarrollo de un caso logístico real con datos de transporte.",
  "2": "Recordemos brevemente cómo encaja esta unidad en el panorama general de la asignatura.",
  "3": "La evaluación de esta unidad es el 10% de su nota final y se basa en la entrega de un script Python documentado.",
  "4": "Todo lo que veamos de condicionales, bucles y pandas está orientado a lograr esta competencia.",
  "5": "Comenzaremos con la sintaxis fundamental y cómo Python guarda la información en memoria.",
  "6": "Toda la información del mundo real se traduce a estos tipos primitivos.",
  "7": "Cuando un dato aislado no basta, usamos colecciones. Aquí comparamos listas, tuplas y diccionarios.",
  "8": "En Python la limpieza visual es obligatoria. No hay llaves, solo espacios.",
  "9": "Veamos si comprendimos la inmutabilidad.",
  "10": "Pasamos a la toma de decisiones lógicas y la repetición de tareas.",
  "11": "A veces necesitamos más de dos opciones (True/False). Para eso usamos elif.",
  "12": "Compararemos el ciclo iterativo por excelencia (for) con el condicional (while).",
  "13": "Break y Continue nos permiten optimizar o saltar lógica innecesaria dentro de un bucle.",
  "14": "Cómo empaquetar código para que sea reutilizable y mantenible.",
  "15": "Desglosaremos las partes clave de una definición de función en Python.",
  "16": "Justificamos su uso para preparar mentalmente el trabajo modular que pide la U1.",
  "17": "El plato fuerte para la ciencia de datos tabulares.",
  "18": "Son el estándar de la industria en Python.",
  "19": "Mostramos cómo se ve un script típico de análisis de datos de principio a fin.",
  "20": "Algunos métodos críticos mostrados en formato mosaico.",
  "21": "Matplotlib permite ilustrar resultados de forma contundente.",
  "22": "Pequeña prueba sobre entrada de datos.",
  "23": "Llevaremos todo lo aprendido a un ejercicio realista enfocado en el sector público (Transportes).",
  "24": "El caso requiere analizar datos Bip! para proponer refuerzos de flota.",
  "25": "Comprender la forma de las columnas es el paso 0 de cualquier análisis.",
  "26": "Los datos tienen inconsistencias que el script debe solucionar.",
  "27": "Este es el núcleo de la evaluación. Transformar variables en categorías.",
  "28": "El script debe emitir una recomendación basada en los datos limpios.",
  "29": "Cierre con lecturas y material anexo de la plataforma.",
  "30": "Despedida."
};