window.speakerNotes = [
  "Bienvenidos a la Unidad 1. Durante las próximas semanas, pasaremos de ver el código simplemente como 'algo que funciona' a entenderlo como un ecosistema donde la calidad debe garantizarse de forma metódica y estructurada.",
  "Nuestro viaje se divide en 4 paradas estratégicas: Fundamentos y Principios, Niveles Inferiores (Unitario/Integración), Niveles Superiores (Sistema/Aceptación) y finalmente Tipos de Pruebas y Técnicas de Diseño.",
  "Históricamente, el testing era la fase final, un 'control de calidad' antes de salir a producción. Hoy, el testing es un proceso continuo. Es una forma de pensar.",
  "Parecen sinónimos, pero no lo son. Podemos construir un software perfecto, sin bugs, rapidísimo (Verificación exitosa)... que no le sirva de nada al usuario (Validación fallida).",
  "El humano comete el Error por cansancio o distracción. Eso inyecta un Defecto estático en el código. Si ese código se ejecuta bajo ciertas condiciones, ocurre la Falla observable por el usuario.",
  "No podemos probar todas las combinaciones posibles, tomaría años. Por eso aplicamos testing temprano (Shift-Left) y priorizamos basado en riesgo.",
  "Si siempre corremos las mismas pruebas automatizadas, tarde o temprano dejarán de encontrar errores. Hay que renovar el enfoque constantemente (Paradoja del Pesticida).",
  "Arreglar un error en la toma de requisitos cuesta 1 dólar. Arreglarlo en producción puede costar 100 veces más, sin contar el daño a la reputación de la empresa.",
  "Tómense 30 minutos. Necesito que mapeen el desastre de su caso asignado usando la taxonomía de Error, Defecto y Falla. Luego discutimos en el foro.",
  "Vamos a adentrarnos en los cimientos del software. Aquí hablaremos de código y de cómo los desarrolladores aseguran que las piezas individuales funcionan antes de armar el rompecabezas.",
  "Mike Cohn propuso esta pirámide. Nos dice que debemos tener muchísimas pruebas unitarias rápidas y baratas, y muy pocas pruebas de UI o E2E, porque son lentas y frágiles.",
  "Es la base del código de calidad. Evalúan pequeñas piezas aisladas (funciones, métodos). Son responsabilidad absoluta del desarrollador.",
  "¿Qué pasa si mi función consulta una base de datos que está caída? Mi prueba fallará, pero no por mi función. Por eso 'aislamos' usando simuladores como Mocks y Stubs.",
  "Una vez que sabemos que los ladrillos (unidades) son sólidos, ¿qué pasa cuando los juntamos? Aquí verificamos las interfaces y la comunicación entre servicios.",
  "Big Bang es integrar todo al final y rezar. No lo recomendamos. Es mejor ir de abajo hacia arriba (Bottom-Up) probando primero la BD y repositorios, o de arriba hacia abajo (Top-Down).",
  "En la integración, enviaríamos un pago simulado a Stripe para verificar si nuestro sistema procesa la respuesta JSON correctamente.",
  "Resuelvan los ejercicios del Cuaderno U1 para consolidar el uso de Mocks, Stubs y estrategias Top-Down vs Bottom-Up.",
  "Hemos probado funciones y APIs. Ahora el producto está armado. Entra el rol fuerte de QA y del cliente para probar el sistema como un todo integrado.",
  "Aquí ya no probamos código o APIs aisladas. Probamos el producto completo, orquestado y corriendo en un entorno lo más parecido a producción posible.",
  "Que el sistema de matrícula funcione es funcional. Que soporte a 5000 alumnos al mismo tiempo sin caerse, es no funcional (Rendimiento/Estrés).",
  "Llegamos a la cima de la pirámide. El software funciona, pero ¿lo acepta quien paga por él? Son las pruebas de validación final.",
  "En el Modelo en V, cada fase de desarrollo tiene su contraparte de pruebas. El diseño arquitectónico se valida con pruebas de integración, y los requisitos con aceptación.",
  "Diseñar criterios UAT los obliga a pensar como el usuario, no como el desarrollador que busca un HTTP 200.",
  "Entramos a las técnicas. Ahora veremos las 'cajas', que definen la visibilidad que tiene el QA sobre el código fuente.",
  "Aquí el ingeniero de calidad abre el capó. Entiende los if, loops y la arquitectura. Busca lograr la mayor cobertura de código posible.",
  "Al tester de Caja Negra no le importa si está programado en Python o Java. Le importa si meto la tarjeta de crédito (entrada), me da el ticket (salida).",
  "La partición de equivalencia y el análisis de valores límite son fundamentales. Si el sistema acepta edad de 18 a 65, los bugs siempre estarán en los bordes: probamos el 17, 18, 65 y 66.",
  "El terror del desarrollador: arreglas un botón y rompes el carrito de compras. Las pruebas de regresión son tests automatizados que aseguran que el código antiguo sigue funcionando después de un cambio nuevo.",
  "El mercado exige automatización. Playwright y Cypress han desplazado a Selenium en pruebas E2E modernas. Para APIs, Postman y RestAssured son el estándar.",
  "En equipos, discutiremos 10 escenarios. Por ejemplo, medir el tiempo de carga de un servidor web. ¿Qué tipo y nivel de prueba es?",
  "Para la nota de esta unidad, enfrentarán un caso de sistema real. Deberán justificar qué niveles y tipos aplicar y escribir 3 casos de prueba estructurados.",
  "Aquí tenemos la Tabla Periódica de Testing, que resume de manera visual el ecosistema de herramientas de QA. Fíjense cómo están agrupadas por categoría: unitarias, integración, E2E, seguridad y rendimiento.",
  "Finalmente, este Mapa Interactivo muestra la taxonomía completa de las pruebas de software. Pueden explorarlo para ver cómo se ramifican las pruebas funcionales y no funcionales."
];
